### ISSUE TITLE
Disable when macro recording or executing

### ISSUE THREAD

**Issue by levouh** [ja-ford/delaytrain.nvim#1]
Obviously this is something that I could do myself with the commands exported by this plugin, however native functionality to ignore timeouts when:

```lua
vim.fn.reg_recording() -- If recording a macro
vim.fn.reg_executing() -- If executing a macro
```

return something other than `""` (along with a configuration option to toggle this behavior perhaps) seems like a good thing to have built-in.

**Comment by ja-ford** [comment]
Totally agree on macro execution, there's no real reason to have DelayTrain enabled when a macro is being executed so I created a PR to bake this into the normal functionality. I'll leave the PR around for a day or two pending any comments before merging.

For macro recording, I think in most cases it would still be helpful to try and break habits whether you're recording a macro or navigating normally. I don't want to add too many edge cases to this plugin but adding the following to your config should accomplish this for you:

```lua
vim.api.nvim_create_autocmd("RecordingEnter", {command = "DelayTrainDisable"})
vim.api.nvim_create_autocmd("RecordingLeave", {command = "DelayTrainEnable"})
```

**Comment by levouh** [comment]
Both work for me, appreciate the input and the plugin @ja-ford.
