### ISSUE TITLE
Disable for NerdTree or nvim-tree

### ISSUE THREAD

**Issue by anatoly-kor** [ja-ford/delaytrain.nvim#2]
How I can ignore behavior for NerdTree or nvim-tree?

**Comment by ja-ford** [comment]
You should be able to use a combination of the `DelayTrainEnable`/`Disable` commands and the `BufEnter`/`Leave` events. I tried the following out in my local environment and this seemed to work:

```lua
vim.api.nvim_create_autocmd({"BufEnter", "BufWinEnter"}, {
  pattern = {"NvimTree*"},
  command = "DelayTrainDisable",
})
vim.api.nvim_create_autocmd({"BufLeave", "BufWinLeave"}, {
  pattern = {"NvimTree*"},
  command = "DelayTrainEnable",
})
```

**Comment by pogopaule** [comment]
@ja-ford Would love to have a config option. "Feels" a bit cleaner to me. Others have something like this too. e.g. https://github.com/nvim-lualine/lualine.nvim#default-configuration `disabled_filetype`

**Comment by ja-ford** [comment]
Sorry for not updating this sooner. This is actually being worked on in #5 . It'll support a list of wildcard filetypes that you can add directly to the DelayTrain config. I just need to do a final review when I have some downtime and then merge it. I'll reopen this issue for now and close it once this is merged.

**Comment by ja-ford** [comment]
Version 1.0.0 has been released with this feature. You can now pass a list of wildcard filetypes using `ignore_filetypes` in your delaytrain config. You can see some examples in the readme/help doc.
